server:
    port: $[server.port]
    uri-encoding: utf-8
    session:
      timeout: $[server.session.timeout]
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: $[http.multipart.max-file-size]
      max-request-size: $[http.multipart.max-request-size]
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: $[datasource.url]
    username: $[datasource.username]
    password: $[datasource.password]
    druid:
      initial-size: $[druid.initial-size]
      min-idle: $[druid.min-idle]
      max-active: $[druid.max-active]
      #配置获取连接等待超时的时间
      max-wait: $[druid.max-wait]
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: $[druid.time-between-eviction-runs-millis]
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: $[druid.min-evictable-idle-time-millis]
      validation-query: $[druid.validation-query]
      test-while-idle: $[druid.test-while-idle]
      test-on-borrow: $[druid.test-on-borrow]
      test-on-return: $[druid.test-on-return]
      pool-prepared-statements: $[druid.pool-prepared-statements]
      max-pool-prepared-statement-per-connection-size:  $[druid.max-pool-prepared-statement-per-connection-size]
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connection-properties: $[druid.connection-properties]
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: $[druid.use-global-data-source-stat]
      filter:
        wall:
          enabled: $[druid.filter.wall.enabled]
          config:
            multi-statement-allow: $[druid.filter.wall.enabled.config.multi-statement-allow]
        stat:
          enabled: $[druid.filter.stat.enabled]
        slf4j:
          enabled: $[druid.filter.slf4j.enabled]
  redis:
      host: $[redis.host]
      port: $[redis.port]
      password: $[redis.password]
      # 连接超时时间（毫秒）
      timeout: $[redis.timeout]
      pool:
          # 连接池中的最大空闲连接
          max-idle: $[redis.pool.max-idle]
          # 连接池中的最小空闲连接
          min-idle: $[redis.pool.min-idle]
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: $[redis.pool.max-active]
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: $[redis.pool.max-wait]
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/module/**/*Mapper.xml
  typeAliasesPackage: com.mea.site.**.model
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  not-empty: false
  identity: MYSQL
  mappers:
        - com.mea.site.common.base.mapper.BaseMapper
mea:
  uploadPath: $[glad.uploadPath]
logging:
  level:
    com.mea.site: $[logging.level]
  path: $[logging.path]